Repository tari-project/tari-dot-com, pull requests merged in 2023-12, with the labels that each got.

#188 feat: filter downloads by architecture
  _data/downloads.yml
  _includes/downloads.html
  assets/css/downloads.css
  assets/js/downloads.js
Labels: P-acks_required

#190 fix: downloads latest file selection
  assets/css/downloads.css
  assets/js/downloads.js
Labels: CR-insufficient_context, P-acks_required

#191 feat: new post
  _updates/2023-12-14-update-124.md
Labels: CR-insufficient_context, P-acks_required

#192 feat: update 124
  _updates/2023-12-20-update-124.md
Labels: CR-insufficient_context
