Repository tari-project/tari-dot-com, pull requests merged in 2023-07, with the labels that each got.

#166 feat: update 112
  _updates/2023-07-05-update-112.md
Labels: P-acks_required, P-reviews_required

#167 Add update link
  _includes/side-navigation.html
Labels: CR-insufficient_context

#168 Update 113
  _updates/2023-07-05-update-113.md
  assets/updates/docs/tariscript.pdf
  assets/updates/img/guimaraes_sm.jpg
  assets/updates/img/tariscript_paper_screenshot.png
Labels: P-merge

#169 feat: add update 114
  _updates/2023-07-21-update-114.md
  assets/updates/img/update-114-1.png
  assets/updates/img/update-114-2.png
  assets/updates/img/update-114-3.png
  assets/updates/img/update-114-4.png
Labels: CR-insufficient_context, P-acks_required

#170 feat: substack newsletter subscription forms
  _includes/newsletter-subscribe.html
  _includes/social-links.html
  assets/css/styles.css
  subscribe.html
Labels: P-acks_required
