Repository tari-project/tari-dot-com, pull requests merged in 2023-06, with the labels that each got.

#164 chore: remove matomo
  _includes/head.html
Labels: P-merge, P-reviews_required

#162 update 110 HW possibilities
  _updates/2023-05-17-update-110.md
Labels: CR-insufficient_context, P-merge

#165 feat: update 111 - DAN consensus, take two
  _updates/2023-06-30-update-111.md
Labels: CR-insufficient_context, P-merge, P-acks_required
