Repository tari-project/tari-dot-com, pull requests merged in 2024-11, with the labels that each got.

#264 Higher quality video background for universe hero
  _includes/head.html
  assets/css/universe.css
  index.html
Labels: P-acks_required, P-reviews_required

#231 feat: add exchange guide
  _lessons/09_adding_tari_to_your_exchange.md
  assets/lessons/img/tariexchangeguide/tariexchangeguide_wallet_addresses.png
Labels: CR-insufficient_context, P-acks_required

#268 Correct Headers in 138
  _updates/2024-11-26-update-138.md
Labels: CR-insufficient_context
