Repository tari-project/tari-dot-com, pull requests merged in 2024-10, with the labels that each got.

#237 feat: add update 134 v2
  _updates/2024-10-04-update-134.md
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#240 Fix: Remove duplicate heading on Dev Update
  _updates/2024-10-04-update-134.md
Labels: CR-insufficient_context

#241 fix: wording changes
  _updates/2024-10-04-update-134.md
Labels: CR-insufficient_context

#242 fix: fix paths and link
  _lessons/07_add_new_localizations.md
  _updates/2024-10-04-update-134.md
Labels: CR-insufficient_context

#243 fix: formatting and reordering of lessons
  assets/css/styles.css
  index.html
  lessons.html
Labels: P-acks_required, P-reviews_required

#239 feat: add a "Setting up your development environment guide" for contribution documentation
  _lessons/setting-up-development-environment.md
  assets/lessons/img/settingupenviro_lesson/clonefromgithub.png
  assets/lessons/img/settingupenviro_lesson/gitclone_commandprompt.png
  assets/lessons/img/settingupenviro_lesson/remoterepo.png
  assets/lessons/img/settingupenviro_lesson/repoorigin.png
Labels: P-acks_required, P-reviews_required

#244 fix: renamed setting up development environment guide file to be consistent with letters and added style data
  _lessons/08_setting_up_development_environment.md
Labels: P-acks_required, P-reviews_required

#245 fix: corrected link to development environment setup guide to reflect new file name.
  _lessons/07_add_new_localizations.md
Labels: P-acks_required

#246 feat: dev update styles
  _layouts/update.html
  _updates/2024-06-11-update-132.md
  _updates/2024-07-22-update-133.md
  _updates/2024-10-04-update-134.md
  assets/css/styles.css
  assets/updates/img/dev-update.jpg
Labels: P-acks_required, P-reviews_required

#248 feat: dev update thumbnails
  _includes/updates-area.html
  _updates/2024-07-22-update-133.md
  _updates/2024-10-04-update-134.md
  assets/updates/img/dev-update.jpg
  assets/updates/img/update-background-blue.jpg
  assets/updates/img/update-background.jpg
Labels: P-acks_required, P-reviews_required

#249 feat: pagination for updates
  _layouts/update.html
  assets/css/styles.css
  assets/js/pagination.js
  updates.html
Labels: P-acks_required, P-reviews_required

#251 fix: delete update 135
  _updates/2024-10-10-update-135.md
Labels: CR-insufficient_context

#252 fix: date margin
  assets/css/styles.css
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#254 fix: date and minor typo.
  _updates/2024-10-11-update-135.md
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#255 fix: corrected date and sentence on dev update
  _updates/2024-10-14-update-135.md
Labels: CR-insufficient_context

#257 feat: Tari Universe hero section added to the homepage
  .prettierrc
  _includes/head.html
  assets/css/styles.css
  assets/css/universe.css
  assets/img/universe/background.png
  assets/img/universe/gem.png
  index.html
Labels: P-acks_required, P-reviews_required

#260 feat: universe Hero background video & text animation
  _includes/head.html
  assets/css/universe.css
  assets/vid/universe-background.mp4
  index.html
Labels: P-acks_required
