Repository tari-project/tari-dot-com, pull requests merged in 2024-02, with the labels that each got.

#203 feat: launchpad m1 download links
  _data/launchpad_downloads.yml
Labels: CR-insufficient_context, P-acks_required

#204 feat: update mining guide
  _data/launchpad_downloads.yml
  downloads.html
Labels: P-acks_required

#206 feat: add launchpad mining guide
  _includes/head.html
  assets/css/notes.css
  assets/launchpad/dashboard.png
  assets/launchpad/miner1p.webp
  assets/launchpad/miner2p.webp
  launchpad-guide.html
  launchpad-guide.md
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#207 fix: add max width for content area
  assets/css/styles.css
  launchpad-guide.md
Labels: CR-insufficient_context, P-acks_required

#208 fix: blog width
  assets/css/styles.css
Labels: CR-insufficient_context, P-acks_required

#209 fix: broken link
  _updates/2021-11-11-update-63.md
Labels: CR-insufficient_context, P-acks_required

#210 feat: update 10,000,000
  _updates/2023-07-05-update-112.md
  _updates/2024-02-14-update-128.md
  assets/updates/img/audit-issue-count.png
  assets/updates/img/audit.webp
  assets/updates/img/audit_bg.webp
  assets/updates/img/blockchain-audit.png
Labels: P-merge, P-reviews_required

#211 feat: update mining guide
  assets/launchpad/console-wallet.png
  launchpad-guide.md
Labels: CR-insufficient_context

#212 feat: tari launchpad video guide
  launchpad-guide.md
Labels: CR-insufficient_context

#213 feat: update 129
  _updates/2024-02-23-update-129.md
  launchpad-guide.md
Labels: CR-insufficient_context, P-acks_required, P-reviews_required
