Repository tari-project/tari-dot-com, pull requests merged in 2024-01, with the labels that each got.

#193 feat: add search tool to kapa
  _config.yml
  _includes/kapa.html
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#194 docs: add update 125
  _updates/2024-01-10-update-125.md
  assets/img/posts/hacker.webp
  assets/img/posts/hacker2.webp
  assets/updates/img/hacker_bg.webp
Labels: CR-insufficient_context

#196 chore: add png logo asset
  assets/img/tari-logo.png
Labels: CR-insufficient_context

#197 feat: update 126 - tlu 2.0
  _updates/2024-01-17-update-126.md
  assets/updates/img/new_tlu.webp
  assets/updates/img/new_tlu.xcf
  assets/updates/img/new_tlu_bg.webp
  assets/updates/img/student.webp
  assets/updates/img/tlu2.webp
  assets/updates/img/tlu_1.0.webp
  assets/updates/img/tlu_tutorial.webp
Labels: CR-insufficient_context, P-acks_required

#199 feat: mining update
  _updates/2024-01-24-update-127.md
Labels: CR-insufficient_context, P-acks_required

#201 feat: download button error handling
  assets/js/downloads.js
Labels: P-acks_required

#195 feat: add launchpad download section
  _data/launchpad_downloads.yml
  _data/suite_downloads.yml
  _includes/download_launchpad.html
  _includes/download_suite.html
  _includes/head.html
  assets/css/styles.css
  assets/img/downloads/launchpad-mac.mp4
  assets/img/downloads/launchpad-mac.png
  assets/img/downloads/launchpad-ubuntu.mp4
  assets/img/downloads/launchpad-ubuntu.png
  assets/img/downloads/launchpad-window.png
  assets/img/downloads/launchpad-windows.mp4
  assets/img/downloads/launchpad-windows.png
  assets/js/downloads.js
  downloads.html
  index.html
  launchpad.html
Labels: P-merge

#202 fix: typo
  _data/launchpad_downloads.yml
  _data/suite_downloads.yml
Labels: CR-insufficient_context, P-acks_required
